### ISSUE TITLE
Fingerprint

### ISSUE THREAD

**Issue by gurri11** [F1xy-kernels/RAPHAEL_Kernel#1]
K20Pro Miui12 fingerprint scanner is not working

**Comment by YaroST12** [comment]
![image](https://user-images.githubusercontent.com/26440429/97800394-f1cd0b00-1c45-11eb-8725-3eb81f20f7fe.png)

**Comment by Lacentix** [comment]
Are you aware that this kernel doesn't support miui12 or do we need to include IQ oc for you?
