### ISSUE TITLE
Project discontinued?

### ISSUE THREAD

**Issue by hexclann** [F1xy-kernels/RAPHAEL_Kernel#3]
I have seen many posts about this kernel for Raphael is being discontinued and there will be no updates in the future. Is it true?

**Comment by YaroST12** [comment]
Yes.

**Comment by hexclann** [comment]
The work on davinci has been resumed, is there any hopes for Raphael?

**Comment by YaroST12** [comment]
> The work on davinci has been resumed, is there any hopes for Raphael?

Was it?

**Comment by hexclann** [comment]
Nvm, the repo is new and looks like it supports only Android 11

**Comment by YaroST12** [comment]
> Nvm, the repo is new and looks like it supports only Android 11

Davinci repo isn't mine, it's by my friend who's another member of F1xy-kernels.
